#coreTools config
#Thu Jun 18 18:38:35 CST 2026
ai.model.0.alias=deepseek-v4-pro
ai.model.0.key=sk-4bea13e552a24c9490130e072aa4985c
ai.model.0.name=deepseek-v4-pro
ai.model.0.url=https\://api.deepseek.com
ai.model.count=1
batch.enc.backup=false
batch.enc.dst=UTF-8
batch.enc.src=GBK
batch.rename.case=全小写
batch.rename.delend=3
batch.rename.delstart=0
batch.rename.includeext=false
batch.rename.insertpos=0
batch.rename.mode=查找替换
batch.rename.seqdigits=3
batch.rename.seqprefix=file_
batch.rename.seqstart=1
batch.replace.backup=false
batch.replace.case=false
batch.replace.encoding=UTF-8
batch.replace.regex=false
convert.crc.algo=CRC8
convert.crc.format=文本 (UTF-8)
convert.crypto.algo=AES
convert.crypto.mode=ECB
convert.crypto.pad=PKCS5Padding
convert.str.encFrom=UTF-8
convert.str.encTo=GBK
convert.ts.unit=秒
convert.ts.zone=北京时间 (UTC+8)
diag.dns.host=www.baidu.com
diag.ping.count=4
diag.ping.host=www.baidu.com
diag.ping.timeout=1000
font.color=-1
font.family=Microsoft YaHei
font.size=13
hexviewer.bytesPerLine=16 字节/行
http.url=http\://httpbin.org/get
logviewer.enc=UTF-8
logviewer.level=全部
redis.connection.count=0
scan.ip=127.0.0.1
scan.port.end=10000
scan.port.interval=5
scan.port.loop=false
scan.port.start=1
scan.subnet=192.168.4.
scan.subnet.interval=5
scan.subnet.loop=false
scan.subnet.ports=80,443,22,3389,8080,23,21,25,554,8554,8000,8888,37777,34567,9527,8899,554,7070
serial.baud=115200
serial.dataBits=8
serial.enc=UTF-8
serial.flowControl=无
serial.parity=无
serial.stopBits=1
ssh.conn.count=0
ssh.hostkey.count=0
tcpClient.host=192.168.4.66
tcpClient.port=9901
tcpServer.port=9901
telnet.host=127.0.0.1
telnet.port=23
theme=com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme
udpClient.host=192.168.4.66
udpClient.port=9000
udpServer.enc=UTF-8
udpServer.format=明文 Text
udpServer.port=9900
videoStream.host=127.0.0.1
videoStream.port=9000
videoStream.rtsp=rtmp\://liteavapp.qcloud.com/live/liteavdemoplayerstreamid
ws.heartbeat=30
ws.path=/ws
ws.port=8080
ws.url=ws\://127.0.0.1\:8080/ws
