#coreTools config
#Sat Jun 13 19:02:54 CST 2026
main.host=127.0.0.1
main.port=9000
main.rtsp=rtmp\://liteavapp.qcloud.com/live/liteavdemoplayerstreamid
tcpClient.host=192.168.4.66
tcpClient.port=9901
tcpServer.port=9901
theme=com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme
udpClient.host=192.168.4.66
udpClient.port=9000
udpServer.enc=UTF-8
udpServer.format=明文 Text
udpServer.port=9900
videoStream.host=127.0.0.1
videoStream.port=9000
videoStream.rtsp=rtmp\://liteavapp.qcloud.com/live/liteavdemoplayerstreamid
