#coreTools config
#Wed Jun 17 01:22:51 CST 2026
batch.enc.backup=false
batch.enc.dst=UTF-8
batch.enc.src=GBK
batch.rename.case=全小写
batch.rename.delend=3
batch.rename.delstart=0
batch.rename.includeext=false
batch.rename.insertpos=0
batch.rename.mode=查找替换
batch.rename.seqdigits=3
batch.rename.seqprefix=file_
batch.rename.seqstart=1
batch.replace.backup=false
batch.replace.case=false
batch.replace.encoding=UTF-8
batch.replace.regex=false
convert.crc.algo=累加和 (Sum8)
convert.crc.format=文本 (UTF-8)
convert.crypto.algo=DES
convert.crypto.mode=ECB
convert.crypto.pad=NoPadding
convert.str.encFrom=UTF-8
convert.str.encTo=UTF-8
convert.ts.unit=毫秒
convert.ts.zone=北京时间 (UTC+8)
db.dbName=test
db.host=127.0.0.1
db.port=3306
db.type=MySQL
db.user=root
dbconn.list=szh,test
dbconn.szh.dbName=test
dbconn.szh.host=127.0.0.1
dbconn.szh.pass=123456
dbconn.szh.port=3306
dbconn.szh.type=MySQL
dbconn.szh.user=root
dbconn.test.dbName=test
dbconn.test.host=127.0.0.1
dbconn.test.pass=123456
dbconn.test.port=3306
dbconn.test.type=MySQL
dbconn.test.user=root
diag.dns.host=www.donaa.cc
diag.ping.count=0
diag.ping.host=www.baidu.com
diag.ping.timeout=1000
font.family=Microsoft YaHei
font.size=12
hexviewer.bytesPerLine=8 字节/行
http.url=http\://httpbin.org/get
logviewer.enc=UTF-8
logviewer.level=全部
main.host=127.0.0.1
main.port=9000
main.rtsp=rtmp\://liteavapp.qcloud.com/live/liteavdemoplayerstreamid
procmon.autoRefresh=false
procmon.portInterval=3s
procmon.procInterval=3s
redis.connection.0.host=127.0.0.1
redis.connection.0.name=test
redis.connection.0.port=6379
redis.connection.count=1
scan.ip=192.168.10.9
scan.port.end=20000
scan.port.interval=3
scan.port.loop=true
scan.port.start=1000
scan.subnet=192.168.10
scan.subnet.interval=3
scan.subnet.loop=true
scan.subnet.ports=80,443,22,3389,8080,22,21
serial.baud=115200
serial.dataBits=8
serial.enc=UTF-8
serial.parity=无
serial.stopBits=1
tcpClient.host=127.0.0.1
tcpClient.nickname=xx
tcpClient.port=9901
tcpServer.port=9901
telnet.host=127.0.0.1
telnet.port=9901
theme=com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme
udpClient.host=127.0.0.1
udpClient.nickname=szh
udpClient.port=9900
udpServer.enc=UTF-8
udpServer.format=明文 Text
udpServer.port=9900
videoStream.host=127.0.0.1
videoStream.port=9000
videoStream.rtsp=rtmp\://liteavapp.qcloud.com/live/liteavdemoplayerstreamid
ws.heartbeat=3
ws.path=/ws
ws.port=8080
ws.url=ws\://127.0.0.1\:8080/ws
